### ISSUE TITLE
17track closed their API for public use

### ISSUE THREAD

**Issue by myxomop3d** [fewieden/MMM-ShipmentTracking#9]
Hello!
17track is not working for now ([link](https://help.17track.net/hc/en-us/articles/235261928-Does-17TRACK-have-API-))
For now it thows:
`
TypeError: Cannot read property '0' of undefined                                                                                                                                                                 at Request.request [as _callback] (D:\programming\gitrepos\MagicMirror\modules\MMM-ShipmentTracking\carriers\17track.js:76:42)                                                                               at Request.self.callback (D:\programming\gitrepos\MagicMirror\modules\MMM-ShipmentTracking\node_modules\request\request.js:185:22)                                                                           at emitTwo (events.js:126:13)                                                                                                                                                                                at Request.emit (events.js:214:7)                                                                                                                                                                            at Request. (D:\programming\gitrepos\MagicMirror\modules\MMM-ShipmentTracking\node_modules\request\request.js:1161:10)                                                                            at emitOne (events.js:116:13)                                                                                                                                                                                at Request.emit (events.js:211:7)                                                                                                                                                                            at IncomingMessage. (D:\programming\gitrepos\MagicMirror\modules\MMM-ShipmentTracking\node_modules\request\request.js:1083:12)                                                                    at Object.onceWrapper (events.js:313:30)                                                                                                                                                                     at emitNone (events.js:111:20)
`

Request returns "301 Moved Permanently"
So, may be we can implement another tracking system?

**Comment by fewieden** [comment]
I planned to support aftership in the future. There is also already a module supporting that one, that you might want to use in the meantime. https://github.com/mykle1/MMM-AfterShip and https://github.com/vanhoekd/MMM-AfterShip

Also it could be that I'll be able to fix the 17track carrier, but currently I have no time for that.
